In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("../data/property_price_regression_practice.csv")
df

,property_type,location,area_sqft,bedrooms,bathrooms,age_years,floor,total_floors,parking,furnishing,distance_to_metro_km,nearby_schools,monthly_maintenance_inr,has_gym,has_security,price_lakhs
0,Builder Floor,Noida,795.0,3,4.0,19.0,3,3,No,Unfurnished,1.36,1,1530.0,Yes,Yes,79.40
1,Builder Floor,Janakpuri,484.0,1,1.0,36.0,18,18,No,Unfurnished,4.27,3,784.0,Yes,Yes,43.76
2,Apartment,Noida,1106.0,3,2.0,37.0,1,14,Yes,Semi-Furnished,0.94,5,2530.0,Yes,Yes,70.97
3,Builder Floor,Paschim Vihar,862.0,2,1.0,18.0,22,22,Yes,Unfurnished,0.14,4,1404.0,No,Yes,97.63
4,Builder Floor,Rohini,873.0,1,1.0,0.0,5,9,Yes,Fully Furnished,2.81,4,2462.0,Yes,Yes,93.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1807,Builder Floor,Gurugram,665.0,1,1.0,4.0,10,11,Yes,Semi-Furnished,0.90,7,1113.0,Yes,Yes,111.36
1808,Independent House,Noida,665.0,1,1.0,10.0,1,3,No,Semi-Furnished,0.79,4,1415.0,No,Yes,86.94
1809,Apartment,Janakpuri,1007.0,3,3.0,14.0,1,5,Yes,Semi-Furnished,1.22,4,1929.0,Yes,Yes,124.23
1810,Apartment,Janakpuri,1492.0,3,3.0,13.0,3,6,No,Fully Furnished,2.53,3,2647.0,No,Yes,116.03
1811,Apartment,Dwarka,1555.0,3,3.0,23.0,8,10,No,Semi-Furnished,1.19,2,3783.0,No,Yes,103.01

In [4]:
# make a copy of df!

In [5]:
df_copy = df.copy()

In [6]:
# general inspection of the dataset

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1812 entries, 0 to 1811
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   property_type            1812 non-null   str
 1   location                 1812 non-null   str
 2   area_sqft                1767 non-null   float64
 3   bedrooms                 1812 non-null   int64
 4   bathrooms                1780 non-null   float64
 5   age_years                1767 non-null   float64
 6   floor                    1812 non-null   int64
 7   total_floors             1812 non-null   int64
 8   parking                  1812 non-null   str
 9   furnishing               1749 non-null   str
 10  distance_to_metro_km     1758 non-null   float64
 11  nearby_schools           1812 non-null   int64
 12  monthly_maintenance_inr  1767 non-null   float64
 13  has_gym                  1785 non-null   str
 14  has_security             1812 non-null   str
 15  price_lakhs              1812 non-null   float64
dtypes: float64(6), int64(4), str(6)
memory usage: 226.6 KB

In [8]:
# null values

In [9]:
col_names = df.columns

for col in col_names:
    null_val = df[col].isna().sum()
    if null_val >= 1:
        print(f'{col}: {null_val} null values')

area_sqft: 45 null values
bathrooms: 32 null values
age_years: 45 null values
furnishing: 63 null values
distance_to_metro_km: 54 null values
monthly_maintenance_inr: 45 null values
has_gym: 27 null values

In [10]:
# numerical cols -> describe()
# to check accuracy and validity!

In [11]:
df.describe()

,area_sqft,bedrooms,bathrooms,age_years,floor,total_floors,distance_to_metro_km,nearby_schools,monthly_maintenance_inr,price_lakhs
count,1767.000000,1812.000000,1780.000000,1767.000000,1812.000000,1812.000000,1758.000000,1812.000000,1767.000000,1812.000000
mean,1216.207697,2.726269,2.684831,14.529145,6.770971,13.328918,2.074534,2.492826,2944.743633,108.066893
std,1050.186212,1.292682,1.269744,10.184600,5.659097,6.568501,1.550365,1.597366,5428.660519,36.112966
min,350.000000,1.000000,1.000000,0.000000,0.000000,2.000000,0.100000,0.000000,500.000000,18.000000
25%,809.000000,2.000000,2.000000,7.000000,2.000000,8.000000,0.900000,1.000000,1665.000000,82.165000
50%,1056.000000,3.000000,3.000000,12.000000,6.000000,13.000000,1.700000,2.000000,2392.000000,102.780000
75%,1439.500000,3.000000,4.000000,19.000000,10.000000,19.000000,2.800000,3.000000,3356.500000,129.502500
max,25000.000000,6.000000,5.000000,55.000000,24.000000,24.000000,12.000000,9.000000,150000.000000,300.580000

In [12]:
# checking for duplicates!

In [13]:
df.duplicated().sum()

np.int64(12)

In [14]:
duplicate_mask = df.duplicated(keep=False)

df[duplicate_mask].sort_values(
    by=df.columns.tolist()
)

,property_type,location,area_sqft,bedrooms,bathrooms,age_years,floor,total_floors,parking,furnishing,distance_to_metro_km,nearby_schools,monthly_maintenance_inr,has_gym,has_security,price_lakhs
318,Apartment,Dwarka,1555.0,3,3.0,23.0,8,10,No,Semi-Furnished,1.19,2,3783.0,No,Yes,103.01
1811,Apartment,Dwarka,1555.0,3,3.0,23.0,8,10,No,Semi-Furnished,1.19,2,3783.0,No,Yes,103.01
598,Apartment,Gurugram,1131.0,3,3.0,12.0,2,3,Yes,Unfurnished,4.28,2,3699.0,Yes,Yes,138.25
1805,Apartment,Gurugram,1131.0,3,3.0,12.0,2,3,Yes,Unfurnished,4.28,2,3699.0,Yes,Yes,138.25
1748,Apartment,Janakpuri,816.0,2,1.0,8.0,8,18,Yes,Semi-Furnished,4.04,4,1263.0,No,Yes,71.21
1803,Apartment,Janakpuri,816.0,2,1.0,8.0,8,18,Yes,Semi-Furnished,4.04,4,1263.0,No,Yes,71.21
1457,Apartment,Janakpuri,1007.0,3,3.0,14.0,1,5,Yes,Semi-Furnished,1.22,4,1929.0,Yes,Yes,124.23
1809,Apartment,Janakpuri,1007.0,3,3.0,14.0,1,5,Yes,Semi-Furnished,1.22,4,1929.0,Yes,Yes,124.23
1131,Apartment,Janakpuri,1492.0,3,3.0,13.0,3,6,No,Fully Furnished,2.53,3,2647.0,No,Yes,116.03
1810,Apartment,Janakpuri,1492.0,3,3.0,13.0,3,6,No,Fully Furnished,2.53,3,2647.0,No,Yes,116.03
425,Apartment,Noida,483.0,1,1.0,11.0,4,6,Yes,Fully Furnished,2.68,4,1552.0,No,No,74.70
1804,Apartment,Noida,483.0,1,1.0,11.0,4,6,Yes,Fully Furnished,2.68,4,1552.0,No,No,74.70
115,Apartment,Noida,938.0,2,3.0,24.0,9,12,Yes,Fully Furnished,0.90,1,1392.0,No,No,97.07
1801,Apartment,Noida,938.0,2,3.0,24.0,9,12,Yes,Fully Furnished,0.90,1,1392.0,No,No,97.07
518,Apartment,Rohini,872.0,2,2.0,39.0,2,6,Yes,Semi-Furnished,2.19,4,1818.0,Yes,Yes,87.53
1806,Apartment,Rohini,872.0,2,2.0,39.0,2,6,Yes,Semi-Furnished,2.19,4,1818.0,Yes,Yes,87.53
1264,Apartment,Uttam Nagar,952.0,1,1.0,14.0,19,19,Yes,Semi-Furnished,1.18,2,2929.0,No,Yes,62.19
1802,Apartment,Uttam Nagar,952.0,1,1.0,14.0,19,19,Yes,Semi-Furnished,1.18,2,2929.0,No,Yes,62.19
1413,Builder Floor,Gurugram,665.0,1,1.0,4.0,10,11,Yes,Semi-Furnished,0.90,7,1113.0,Yes,Yes,111.36
1807,Builder Floor,Gurugram,665.0,1,1.0,4.0,10,11,Yes,Semi-Furnished,0.90,7,1113.0,Yes,Yes,111.36
866,Builder Floor,Noida,2122.0,5,5.0,16.0,1,12,No,Unfurnished,1.40,1,3834.0,No,Yes,159.31
1800,Builder Floor,Noida,2122.0,5,5.0,16.0,1,12,No,Unfurnished,1.40,1,3834.0,No,Yes,159.31
1710,Independent House,Noida,665.0,1,1.0,10.0,1,3,No,Semi-Furnished,0.79,4,1415.0,No,Yes,86.94
1808,Independent House,Noida,665.0,1,1.0,10.0,1,3,No,Semi-Furnished,0.79,4,1415.0,No,Yes,86.94

In [15]:
df = df.drop_duplicates()
df.shape

(1800, 16)

In [16]:
# consistency issues in categorical cols!

In [17]:
cat_cols = df.select_dtypes(exclude=['number']).columns.tolist()

for col in cat_cols:
    print(df[col].value_counts(), end='\n\n')

property_type
Apartment            1048
Builder Floor         567
Independent House     185
Name: count, dtype: int64

location
Rohini           331
Dwarka           266
Noida            255
Uttam Nagar      214
Janakpuri        212
Gurugram         181
Pitampura        171
Paschim Vihar    158
NOIDA              5
 rohini            4
GURUGRAM           3
Name: count, dtype: int64

parking
Yes     1155
No       600
yes       32
 no       13
Name: count, dtype: int64

furnishing
Semi-Furnished     815
Unfurnished        558
Fully Furnished    327
semi furnished      27
Fully furnished     10
Name: count, dtype: int64

has_gym
No     954
Yes    819
Name: count, dtype: int64

has_security
Yes    1477
No      323
Name: count, dtype: int64

In [18]:
df['location'] = df['location'].str.strip().str.lower()
df['location'].value_counts()

location
rohini           335
dwarka           266
noida            260
uttam nagar      214
janakpuri        212
gurugram         184
pitampura        171
paschim vihar    158
Name: count, dtype: int64

In [19]:
df['parking'] = df['parking'].str.strip().str.lower()
df['parking'].value_counts()

parking
yes    1187
no      613
Name: count, dtype: int64

In [20]:
df['furnishing'] = df['furnishing'].str.strip().str.replace(' ', '-').str.lower()
df['furnishing'].value_counts()

furnishing
semi-furnished     842
unfurnished        558
fully-furnished    337
Name: count, dtype: int64

In [21]:
# since we changed some categorical columns to lowercase, let's change to lowercase for the other cols as well!

In [22]:
rem_cat_cols = ['property_type', 'has_gym', 'has_security']

for col in rem_cat_cols:
    df[col] = df[col].str.strip().str.lower()

In [23]:
# numerical validity checking!

In [24]:
df[df['floor'] > df['total_floors']]

Empty DataFrame
Columns: [property_type, location, area_sqft, bedrooms, bathrooms, age_years, floor, total_floors, parking, furnishing, distance_to_metro_km, nearby_schools, monthly_maintenance_inr, has_gym, has_security, price_lakhs]
Index: []

In [25]:
df.nlargest(10, 'area_sqft')

,property_type,location,area_sqft,bedrooms,bathrooms,age_years,floor,total_floors,parking,furnishing,distance_to_metro_km,nearby_schools,monthly_maintenance_inr,has_gym,has_security,price_lakhs
1699,builder floor,paschim vihar,25000.0,1,1.0,6.0,1,4,yes,unfurnished,0.60,1,1747.0,no,yes,115.75
1001,apartment,janakpuri,22000.0,2,3.0,3.0,9,19,yes,fully-furnished,4.23,4,2630.0,no,yes,113.27
791,builder floor,pitampura,18000.0,3,3.0,7.0,6,12,no,semi-furnished,0.84,1,2968.0,yes,yes,137.21
601,builder floor,paschim vihar,15000.0,3,3.0,26.0,6,20,no,fully-furnished,1.80,2,4222.0,yes,yes,147.03
675,apartment,pitampura,4040.0,6,5.0,13.0,14,22,yes,unfurnished,1.05,3,12857.0,no,yes,300.58
449,apartment,uttam nagar,3992.0,6,5.0,1.0,11,13,no,semi-furnished,2.43,3,10100.0,yes,no,257.78
999,builder floor,dwarka,3864.0,6,5.0,16.0,0,14,yes,semi-furnished,3.99,2,12505.0,no,yes,266.91
1228,builder floor,gurugram,3404.0,6,5.0,2.0,6,6,no,fully-furnished,0.29,4,4598.0,yes,no,286.40
648,builder floor,paschim vihar,3278.0,6,5.0,15.0,8,21,yes,unfurnished,0.29,4,8205.0,no,yes,244.00
1782,apartment,dwarka,3144.0,6,5.0,19.0,6,13,yes,fully-furnished,0.59,4,3932.0,yes,yes,246.64

In [26]:
df.nlargest(10, 'monthly_maintenance_inr')

,property_type,location,area_sqft,bedrooms,bathrooms,age_years,floor,total_floors,parking,furnishing,distance_to_metro_km,nearby_schools,monthly_maintenance_inr,has_gym,has_security,price_lakhs
1393,builder floor,rohini,1477.0,3,2.0,16.0,0,19,no,semi-furnished,0.61,0,150000.0,no,yes,130.29
1301,apartment,uttam nagar,1017.0,3,2.0,3.0,7,14,yes,unfurnished,0.96,5,120000.0,no,yes,86.76
280,apartment,rohini,976.0,2,2.0,10.0,7,10,yes,semi-furnished,2.09,1,90000.0,no,yes,95.87
1047,apartment,noida,944.0,3,3.0,10.0,4,18,yes,unfurnished,4.48,2,75000.0,no,yes,86.81
675,apartment,pitampura,4040.0,6,5.0,13.0,14,22,yes,unfurnished,1.05,3,12857.0,no,yes,300.58
999,builder floor,dwarka,3864.0,6,5.0,16.0,0,14,yes,semi-furnished,3.99,2,12505.0,no,yes,266.91
553,apartment,gurugram,3036.0,6,5.0,15.0,3,20,yes,semi-furnished,2.84,1,10156.0,yes,yes,215.95
449,apartment,uttam nagar,3992.0,6,5.0,1.0,11,13,no,semi-furnished,2.43,3,10100.0,yes,no,257.78
1007,builder floor,dwarka,3093.0,6,5.0,26.0,2,16,yes,unfurnished,1.11,4,9612.0,yes,yes,208.39
597,apartment,uttam nagar,2935.0,6,5.0,24.0,0,18,no,fully-furnished,2.40,4,9205.0,yes,yes,204.67

In [27]:
# Check negative values in numerical columns
num_cols = df.select_dtypes(include='number').columns

(df[num_cols] < 0).sum()

area_sqft                  0
bedrooms                   0
bathrooms                  0
age_years                  0
floor                      0
total_floors               0
distance_to_metro_km       0
nearby_schools             0
monthly_maintenance_inr    0
price_lakhs                0
dtype: int64

In [28]:
# unusually high area sqft and maintenance values!!

In [29]:
# Flag unusually large property areas
df[df['area_sqft'] > 10000]

,property_type,location,area_sqft,bedrooms,bathrooms,age_years,floor,total_floors,parking,furnishing,distance_to_metro_km,nearby_schools,monthly_maintenance_inr,has_gym,has_security,price_lakhs
601,builder floor,paschim vihar,15000.0,3,3.0,26.0,6,20,no,fully-furnished,1.80,2,4222.0,yes,yes,147.03
791,builder floor,pitampura,18000.0,3,3.0,7.0,6,12,no,semi-furnished,0.84,1,2968.0,yes,yes,137.21
1001,apartment,janakpuri,22000.0,2,3.0,3.0,9,19,yes,fully-furnished,4.23,4,2630.0,no,yes,113.27
1699,builder floor,paschim vihar,25000.0,1,1.0,6.0,1,4,yes,unfurnished,0.60,1,1747.0,no,yes,115.75

In [30]:
# Flag unusually high maintenance charges
df[df['monthly_maintenance_inr'] > 50000]

,property_type,location,area_sqft,bedrooms,bathrooms,age_years,floor,total_floors,parking,furnishing,distance_to_metro_km,nearby_schools,monthly_maintenance_inr,has_gym,has_security,price_lakhs
280,apartment,rohini,976.0,2,2.0,10.0,7,10,yes,semi-furnished,2.09,1,90000.0,no,yes,95.87
1047,apartment,noida,944.0,3,3.0,10.0,4,18,yes,unfurnished,4.48,2,75000.0,no,yes,86.81
1301,apartment,uttam nagar,1017.0,3,2.0,3.0,7,14,yes,unfurnished,0.96,5,120000.0,no,yes,86.76
1393,builder floor,rohini,1477.0,3,2.0,16.0,0,19,no,semi-furnished,0.61,0,150000.0,no,yes,130.29

In [31]:
# exporting the cleaned dataset

In [32]:
df.to_csv('../data/cleaned_property_price.csv', index=False)